# docker-compose.py

version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    restart: always

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: always

  akhq:
    image: tchiotludo/akhq:latest
    depends_on:
      - kafka
    ports:
      - 8081:8080
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            local-kafka:
              properties:
                bootstrap.servers: "kafka:9092"
    restart: always

  kouncil:
    image: consdata/kouncil:latest
    depends_on:
      - kafka
    ports:
      - 8082:8080
    environment:
      KAFKA_BROKERS: "kafka:9092"
    restart: always

  provectus-kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - 8083:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    restart: always

  create-topic:
    image: python:3.9-slim
    depends_on:
      - kafka
    volumes:
      - ${PWD}:/app # Use absolute path
    working_dir: /app
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    command: >
      sh -c "pip install confluent-kafka &&
             python create_topic.py"

  producer:
    image: python:3.9-slim
    depends_on:
      - kafka
    volumes:
      - ${PWD}:/app # Use absolute path
    working_dir: /app
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    command: >
      sh -c "pip install confluent-kafka &&
             python producer_prototype.py"

  consumer:
    image: python:3.9-slim
    depends_on:
      - kafka
    volumes:
      - ${PWD}:/app # Use absolute path
    working_dir: /app
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    command: >
      sh -c "pip install confluent-kafka &&
             python consumer.py"
  # _______________________________________________-
  # redpanda-console:
  #   image: vectorized/console:latest
  #   depends_on:
  #     - kafka
  #   ports:
  #     - 8083:8083
  #   environment:
  #     KAFKA_BROKERS: "kafka:9092"
  #   restart: always
